# Generated by Django 2.1.7 on 2019-02-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('phonenumber', models.IntegerField(db_index=True)),
                ('deviceId', models.CharField(blank=True, max_length=100, null=True)),
                ('spam', models.BooleanField(default=False)),
                ('no_of_spams_marked', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
